apiVersion: v1
kind: Service
metadata:
  name: clamav
  namespace: sentinel
  labels:
    app.kubernetes.io/name: clamav
    app.kubernetes.io/part-of: sentinel-platform
spec:
  selector:
    app.kubernetes.io/name: clamav
  ports:
    - name: clamd
      port: 3310
      targetPort: 3310
