apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clamav-netpol
  namespace: sentinel
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: clamav
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Tillåt endast sentinel-upload-api att nå ClamAV på port 3310
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: sentinel-upload-api
      ports:
        - protocol: TCP
          port: 3310
  egress:
    # Tillåt DNS
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Tillåt ClamAV att ladda ner virusdefinitioner
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80