apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinel-upload-api
  namespace: sentinel
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
  labels:
    app.kubernetes.io/name: sentinel-upload-api
    app.kubernetes.io/part-of: sentinel-platform
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sentinel-upload.secion.se
      secretName: sentinel-upload-tls
  rules:
    - host: sentinel-upload.secion.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentinel-upload-api
                port:
                  number: 80
